### ISSUE TITLE
Conclusion Matlab

### ISSUE THREAD

**Issue by ungarson** [tezosagorawiki/wiki#1]
Something is wrong with the conclusion:

<img width="1440" alt="Screenshot 2021-03-19 at 19 19 49" src="https://user-images.githubusercontent.com/13982759/111811516-2afdd300-88e8-11eb-9432-1901c60f33f1.png">

It's on Google Chrome, Version 89.0.4389.82 (Official Build) (x86_64)

**Comment by ilanbb1** [comment]
Thanks for pointing this out. This should be resolved now.

**Comment by ungarson** [comment]
@ilanbb1 ill close it then, thanks.
